name: Test Wazuh Rules

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-rules:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install XML validator
        run: sudo apt-get install -y libxml2-utils

      - name: Validate XML rules
        run: |
          for file in rules/*.xml; do
            echo "Validating $file"
            xmllint --noout $file
          done

      - name: Detect changed files
        run: |
          echo "Changed files:"
          git diff --name-only HEAD^ HEAD | grep -E 'rules/.*\.xml|decoders/.*\.xml' || true
