name: Test Wazuh Rules

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-rules:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install XML validator
        run: sudo apt-get install -y libxml2-utils

      - name: Validate XML rules
        run: |
          for file in rules/*.xml; do
            echo "Validating $file"
            xmllint --noout $file
          done

      - name: Detect changed files
        run: |
          echo "Changed files:"
          git diff --name-only HEAD^ HEAD | grep -E 'rules/.*\.xml|decoders/.*\.xml' || true
          
      - name: Notify Slack
        if: always() # Penting: Tetap lapor meski XML error
        env:
          SLACK_WEBHOOK: ${{ secrets.TEST_INT }}
        run: |
          # Menentukan emoji berdasarkan status job
          if [ "${{ job.status }}" == "success" ]; then
            EMOJI="✅"
          else
            EMOJI="❌"
          fi

          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\": \"$EMOJI *WAZUH RULES UPDATE*\n*Status:* ${{ job.status }}\n*Repo:* ${{ github.repository }}\n*Branch:* ${{ github.ref_name }}\n*Commit:* ${{ github.sha }}\"
          }" $SLACK_WEBHOOK
